### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by lvsh2012** [jiran214/GPT-vup#11]
PS C:\python\GPTvup\src> python manager.py run bilibili
Traceback (most recent call last):
  File "manager.py", line 10, in <module>
    from src.core.main import start_thread
  File "C:\python\GPTvup\src\core\main.py", line 14, in <module>
    from src.utils.prompt_temple import get_schedule_task
  File "C:\python\GPTvup\src\utils\prompt_temple.py", line 10, in <module>
    from langchain.prompts import SystemMessagePromptTemplate, HumanMessagePromptTemplate, ChatPromptTemplate
  File "C:\Program Files\Python38\lib\site-packages\langchain\__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\Program Files\Python38\lib\site-packages\langchain\agents\__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "C:\Program Files\Python38\lib\site-packages\langchain\agents\agent.py", line 15, in <module>
    from langchain.agents.tools import InvalidTool
  File "C:\Program Files\Python38\lib\site-packages\langchain\agents\tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "C:\Program Files\Python38\lib\site-packages\langchain\tools\__init__.py", line 39, in <module>
    from langchain.tools.vectorstore.tool import (
  File "C:\Program Files\Python38\lib\site-packages\langchain\tools\vectorstore\tool.py", line 13, in <module>
    from langchain.chains import RetrievalQA, RetrievalQAWithSourcesChain
  File "C:\Program Files\Python38\lib\site-packages\langchain\chains\__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "C:\Program Files\Python38\lib\site-packages\langchain\chains\api\base.py", line 13, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "C:\Program Files\Python38\lib\site-packages\langchain\chains\api\prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "C:\Program Files\Python38\lib\site-packages\langchain\prompts\__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "C:\Program Files\Python38\lib\site-packages\langchain\prompts\chat.py", line 10, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "C:\Program Files\Python38\lib\site-packages\langchain\memory\__init__.py", line 25, in <module>
    from langchain.memory.vectorstore import VectorStoreRetrieverMemory
  File "C:\Program Files\Python38\lib\site-packages\langchain\memory\vectorstore.py", line 10, in <module>
    from langchain.vectorstores.base import VectorStoreRetriever
  File "C:\Program Files\Python38\lib\site-packages\langchain\vectorstores\__init__.py", line 2, in <module>
    from langchain.vectorstores.analyticdb import AnalyticDB
  File "C:\Program Files\Python38\lib\site-packages\langchain\vectorstores\analyticdb.py", line 15, in <module>
    from langchain.embeddings.base import Embeddings
  File "C:\Program Files\Python38\lib\site-packages\langchain\embeddings\__init__.py", line 19, in <module>
    from langchain.embeddings.openai import OpenAIEmbeddings
  File "C:\Program Files\Python38\lib\site-packages\langchain\embeddings\openai.py", line 66, in <module>
    class OpenAIEmbeddings(BaseModel, Embeddings):
  File "pydantic\main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic\fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "C:\Program Files\Python38\lib\typing.py", line 774, in __subclasscheck__
    **return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class**

python3.8, 依赖已安装，运行 python manager.py run bilibili 或者 python manager.py test_net 都是一样的报错

**Comment by jiran214** [comment]
1. https://github.com/imClumsyPanda/langchain-ChatGLM/issues/440#issuecomment-1558546245看到了类似的问题，似乎是langchain的问题
2. 没用虚拟环境的话创建虚拟环境试试

**Comment by jiburan** [comment]
我也遇到了这个问题

**Comment by jiran214** [comment]
https://stackoverflow.com/questions/76313592/import-langchain-error-typeerror-issubclass-arg-1-must-be-a-class#:~:text=The%20error%20message%20suggests%20that%20there%20is%20an,updating%20the%20typing%20module%20to%20the%20latest%20version.
参考这个可以解决
