### ISSUE TITLE
最后的问题，链接bilibili时没问题，抖音就这样了

### ISSUE THREAD

**Issue by tashuozhishinanguimi** [jiran214/GPT-vup#23]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\python\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "D:\python\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "D:\xunihuanjing\GPT-vup-2.0\src\core\main.py", line 36, in dy_producer
    t_loop.run(dy_connect())
  File "D:\xunihuanjing\GPT-vup-2.0\src\utils\utils.py", line 40, in run
    self.loop.run_until_complete(coroutine)
  File "D:\python\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\xunihuanjing\GPT-vup-2.0\src\rooms\douyin.py", line 54, in dy_connect
    async with session.ws_connect("ws://127.0.0.1:7890") as ws:
  File "d:\xunihuanjing\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "d:\xunihuanjing\lib\site-packages\aiohttp\client.py", line 779, in _ws_connect
    resp = await self.request(
  File "d:\xunihuanjing\lib\site-packages\aiohttp\client.py", line 560, in _request
    await resp.start(conn)
  File "d:\xunihuanjing\lib\site-packages\aiohttp\client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "d:\xunihuanjing\lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

**Comment by yangyuan-zhen** [comment]
兄弟帮我看下问题 #26
