### ISSUE TITLE
测试网络环境出现如下错误，应该怎么解决，我用的mac m1，shadowracket 代理

### ISSUE THREAD

**Issue by JackChow6** [jiran214/GPT-vup#8]
Traceback (most recent call last):
  File "/Users/zjk-macminim1/GPT-vup/src/manager.py", line 11, in <module>
    from src.core.main import start_thread
  File "/Users/zjk-macminim1/GPT-vup/src/core/main.py", line 14, in <module>
    from src.utils.prompt_temple import get_schedule_task
  File "/Users/zjk-macminim1/GPT-vup/src/utils/prompt_temple.py", line 10, in <module>
    from langchain.prompts import SystemMessagePromptTemplate, HumanMessagePromptTemplate, ChatPromptTemplate
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/agents/agent.py", line 15, in <module>
    from langchain.agents.tools import InvalidTool
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/agents/tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/tools/__init__.py", line 39, in <module>
    from langchain.tools.vectorstore.tool import (
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/tools/vectorstore/tool.py", line 13, in <module>
    from langchain.chains import RetrievalQA, RetrievalQAWithSourcesChain
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/chains/__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/chains/api/base.py", line 13, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/chains/api/prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/prompts/__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/prompts/chat.py", line 10, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/memory/__init__.py", line 25, in <module>
    from langchain.memory.vectorstore import VectorStoreRetrieverMemory
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/memory/vectorstore.py", line 10, in <module>
    from langchain.vectorstores.base import VectorStoreRetriever
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/vectorstores/__init__.py", line 2, in <module>
    from langchain.vectorstores.analyticdb import AnalyticDB
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/vectorstores/analyticdb.py", line 15, in <module>
    from langchain.embeddings.base import Embeddings
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/embeddings/__init__.py", line 19, in <module>
    from langchain.embeddings.openai import OpenAIEmbeddings
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/embeddings/openai.py", line 66, in <module>
    class OpenAIEmbeddings(BaseModel, Embeddings):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/typing.py", line 847, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
(base) zjk-macminim1@Zjk-MacdeMac-mini src % python manager.py test_net
Traceback (most recent call last):
  File "/Users/zjk-macminim1/GPT-vup/src/manager.py", line 11, in <module>
    from src.core.main import start_thread
  File "/Users/zjk-macminim1/GPT-vup/src/core/main.py", line 14, in <module>
    from src.utils.prompt_temple import get_schedule_task
  File "/Users/zjk-macminim1/GPT-vup/src/utils/prompt_temple.py", line 10, in <module>
    from langchain.prompts import SystemMessagePromptTemplate, HumanMessagePromptTemplate, ChatPromptTemplate
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/agents/agent.py", line 15, in <module>
    from langchain.agents.tools import InvalidTool
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/agents/tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/tools/__init__.py", line 39, in <module>
    from langchain.tools.vectorstore.tool import (
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/tools/vectorstore/tool.py", line 13, in <module>
    from langchain.chains import RetrievalQA, RetrievalQAWithSourcesChain
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/chains/__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/chains/api/base.py", line 13, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/chains/api/prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/prompts/__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/prompts/chat.py", line 10, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/memory/__init__.py", line 25, in <module>
    from langchain.memory.vectorstore import VectorStoreRetrieverMemory
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/memory/vectorstore.py", line 10, in <module>
    from langchain.vectorstores.base import VectorStoreRetriever
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/vectorstores/__init__.py", line 2, in <module>
    from langchain.vectorstores.analyticdb import AnalyticDB
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/vectorstores/analyticdb.py", line 15, in <module>
    from langchain.embeddings.base import Embeddings
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/embeddings/__init__.py", line 19, in <module>
    from langchain.embeddings.openai import OpenAIEmbeddings
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/site-packages/langchain/embeddings/openai.py", line 66, in <module>
    class OpenAIEmbeddings(BaseModel, Embeddings):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/Users/zjk-macminim1/opt/anaconda3/lib/python3.9/typing.py", line 847, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

**Comment by JackChow6** [comment]
i get it
