### ISSUE TITLE
出现错误，运行python，python版本是3.9

### ISSUE THREAD

**Issue by JackChow6** [jiran214/GPT-vup#9]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/zjk-macminim1/GPT-vup/src/core/main.py", line 30, in bl_producer
    t_loop.run(r.connect())
  File "/Users/zjk-macminim1/GPT-vup/src/utils/utils.py", line 33, in run
    self.loop.run_until_complete(coroutine)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/zjk-macminim1/GPT-vup/venv/lib/python3.9/site-packages/bilibili_api/live.py", line 657, in connect
    await self.__main()
  File "/Users/zjk-macminim1/GPT-vup/venv/lib/python3.9/site-packages/bilibili_api/live.py", line 688, in __main
    self.__room_real_id = (await room.get_room_play_info())["room_id"]
  File "/Users/zjk-macminim1/GPT-vup/venv/lib/python3.9/site-packages/bilibili_api/live.py", line 126, in get_room_play_info
    resp = await request(api['method'], api['url'], params=params, credential=self.credential)
  File "/Users/zjk-macminim1/GPT-vup/venv/lib/python3.9/site-packages/bilibili_api/utils/network.py", line 111, in request
    async with session.request(**config) as resp:
  File "/Users/zjk-macminim1/GPT-vup/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Users/zjk-macminim1/GPT-vup/venv/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Users/zjk-macminim1/GPT-vup/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/zjk-macminim1/GPT-vup/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/zjk-macminim1/GPT-vup/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/Users/zjk-macminim1/GPT-vup/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/Users/zjk-macminim1/GPT-vup/venv/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 814, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown

**Comment by JackChow6** [comment]
i get it by change py3.8, lazy
